"use client";

import { useEffect, useState } from "react";
import { Link2, ShieldCheck, StickyNote } from "lucide-react";
import type { Note } from "@/lib/crm";
import { THEMES, THEME_VAR_KEYS } from "@/lib/settings";
import type { ThemeKey } from "@/lib/settings";

function toHtmlBlocks(html: string): string {
  if (/<\/?[a-z][\s\S]*>/i.test(html)) return html;
  if (!html.trim()) return "";
  return html
    .split(/\r?\n/)
    .map((line) => `<div>${line.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")}</div>`)
    .join("");
}

export default function ShareNotePage({ params }: { params: Promise<{ id: string }> }) {
  const [note, setNote] = useState<Note | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  // Apply theme
  useEffect(() => {
    fetch("/api/settings")
      .then((r) => r.json())
      .then((data: { theme?: ThemeKey }) => {
        if (data.theme && THEMES[data.theme]) {
          const colors = THEMES[data.theme];
          const root = document.documentElement;
          for (const key of THEME_VAR_KEYS) {
            root.style.setProperty(`--crm-${key}`, colors[key]);
          }
        }
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    (async () => {
      try {
        const { id } = await params;
        // The 'id' param is actually the share token
        const res = await fetch(`/api/shares/${id}`);
        if (!res.ok) {
          setError("Share link not found or has been revoked.");
          return;
        }
        const data = await res.json();
        if (data.docType === "note" && data.doc) {
          setNote(data.doc);
        } else {
          setError("This share link is not for a note.");
        }
      } catch {
        setError("Failed to load note.");
      } finally {
        setLoading(false);
      }
    })();
  }, [params]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-(--crm-bg)">
        <div className="h-9 w-9 animate-spin rounded-full border-2 border-(--crm-soft) border-t-(--crm-mid)" />
      </div>
    );
  }

  if (error || !note) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-(--crm-bg) px-4">
        <div className="w-full max-w-sm rounded-2xl border border-(--crm-border) bg-(--crm-panel) p-8 text-center shadow-sm">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-(--crm-danger-bg) text-(--crm-danger)"><StickyNote size={20} /></div>
          <h1 className="mt-4 text-lg font-semibold text-(--crm-fg)">Note not found</h1>
          <p className="mt-1 text-sm text-(--crm-secondary)">{error || "This note doesn't exist or has been deleted."}</p>
        </div>
      </div>
    );
  }

  const title = note.title || "Untitled note";
  const date = new Date(note.updatedAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen bg-(--crm-bg) px-4 py-8 sm:px-8">
      <div className="mx-auto flex max-w-3xl flex-col items-center gap-5">
        <div className="flex w-full items-center justify-between text-[11px] text-(--crm-muted)">
          <span className="flex items-center gap-1.5"><ShieldCheck size={13} className="text-(--crm-mid)" />Shared note</span>
          <span>webkalcerCRM · webkalcer.com</span>
        </div>

        <div className="w-full">
          <div className="flex aspect-[210/297] w-full flex-col rounded-[3px] border border-(--crm-border-soft) bg-white p-8 shadow-[0_2px_8px_rgba(0,0,0,.05),0_24px_56px_rgba(0,0,0,.14)] sm:p-12">
            <h1 className="w-full bg-transparent text-3xl font-semibold tracking-[-.04em] text-(--crm-fg) sm:text-4xl">{title}</h1>
            <div className="my-6 h-px bg-(--crm-border-soft)" />
            <div
              className="min-h-0 w-full flex-1 overflow-y-auto bg-transparent text-base leading-8 text-(--crm-fg) [&_div]:mb-2 [&_h1]:text-2xl [&_h1]:font-bold [&_h2]:text-xl [&_h2]:font-semibold [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_a]:text-blue-600 [&_a]:underline"
              dangerouslySetInnerHTML={{ __html: toHtmlBlocks(note.content) }}
            />
            <div className="mt-8 border-t border-(--crm-border-soft) pt-3 text-[11px] text-(--crm-muted)">
              Last updated {date}
            </div>
          </div>
        </div>

        <p className="text-[11px] text-(--crm-muted)">Generated by webkalcerCRM · CRM by webkalcer.com</p>
      </div>
    </div>
  );
}
